Plante/config/routes.rb
Rails.application.routes.draw do
  namespace :teacher do
  get 'media_file_handlers/index'
  end

  namespace :teacher do
  get 'media_file_handlers/new'
  end

  namespace :teacher do
  get 'media_file_handlers/create'
  end

  namespace :teacher do
  get 'media_file_handlers/destroy'
  end

  get 'media_file_handlers/index'

  get 'media_file_handlers/new'

  get 'media_file_handlers/create'

  get 'media_file_handlers/destroy'

  devise_for :users

   root 'pages#index'

     resources :pages do 
				get 'show_current_state', on: :collection
				get 'show_parameters', on: :collection
				get 'show_data', on: :collection
				get 'show_data2', on: :collection
				get 'show_media_file', on: :collection
				patch 'update_parameters', on: :collection
		 end
		
		 resources :tests do
		 end	 

    namespace :admin do
      resources :schools do 
		 	get 'index', on: :collection
		 	post 'create', on: :collection
		  end

		  resources :control_cards do
		  end

		  resources :data_cards do
		  end

		  resources :greenhouses do
		  end
    end

		namespace :teacher do
			resources :supervisions do
			end

			resources :media_file_handlers do
			end
		end

  

end

Plante/app/models/school.rb
class School < ActiveRecord::Base
has_one :control_card
has_many :user
has_many :greenhouse
has_and_belongs_to_many :media_file
end

Plante/app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < ApplicationController
	layout "admin"

	def index
		@all_schools = School.all
	end

	def new
		@school = School.new
	end

	def create
		@school = School.new(school_params)
		if @school.save
			flash[:notice] = "Nouvelle école ajoutée"
			redirect_to admin_school_path(@school)
		else
			flash[:notice] = "Erreur lors de l'enregistrement"
			render "new"
		end
	end

	def edit
		@school = School.where(id: params[:id])[0]
	end

	def update
		@school = School.where(id: params[:id].to_i)[0]
		if @school.update_attributes(school_params)
			flash[:notice] = "Mise à jour effectuée"
			redirect_to admin_school_path(@school)
		else
			flash[:notice] = "Erreur lors de la mis à jour"
			render "edit"
		end
	end

	def destroy
		@school = School.where(id: params[:id])[0]
		if @school.destroy
			flash[:notice] = "École supprimée"
			redirect_to admin_schools_path
		else
			flash[:notice] = "Erreur lors de la suppression"
			redirect_to admin_scholls_path
		end
	end

	def show
		@school = School.where(id: params[:id].to_i)[0]
		unless @school.control_card.blank?
			@control_card = ControlCard.where(id: @school.control_card.id)[0]
		end
	end

	private

	def school_params
		params.require(:school).permit(:name, :adress, :town, :zip_code, :contact, :phone_number, :email)
	end
end

Plante/app/helpers/admin/schools_helper.rb
module Admin::SchoolsHelper
end

Plante/app/views/admin/schools/_form.html.erb
<%= form_for @school, url: "create", method: :post do |f| %>
	<%= f.label :name, "Nom de l'école" %> : <%= f.text_field :name, autofocus: true %><br/>
	---<br/>
	<%= f.label :adress, "Adresse" %> : <%= f.text_field :adress, autofocus: true %><br/>
	<%= f.label :town, "Ville" %> : <%= f.text_field :town, autoficus: true %><br/>
	<%= f.label :zip_code, "Code Postal" %> : <%= f.text_field :zip_code, autofocus: true %><br/>
	---<br/>
	<%= f.label :contact, "Nom du contact" %> : <%= f.text_field :contact, autofocus: true %><br/>
	<%= f.label :phone_number, "Numéro de téléphone" %> : <%= f.telephone_field :phone_number, autofocus: true %><br/>
	<%= f.label :email, "Adresse mail" %> : <%= f.email_field :email, autofocus: true %><br/>

	<%= f.submit "Créer" %>
<% end %>

Plante/app/views/admin/schools/_return_link.html.erb
<%= link_to "retour", admin_schools_path, class: 'btn btn-default' %>

Plante/app/views/admin/schools/destroy.html.erb
<h1> DESTROY </h1>

Plante/app/views/admin/schools/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 transparent-co" style="text-align: center">
<h1>Modification des informations d'une école</h1>

<%= form_for @school, url: admin_school_path, method: :patch do |f| %>
<div class="form-group col-md-12">
	<%= f.label :name, "Nom de l'école" %> : <%= f.text_field :name, autofocus: true %><br/>
	---<br/>
	</div>
	<div class="form-group col-md-12">
	<%= f.label :adress, "Adresse" %> : <%= f.text_field :adress, autofocus: true %><br/>
	</div>
	<div class="form-group col-md-12">
	<%= f.label :town, "Ville" %> : <%= f.text_field :town, autoficus: true %><br/>
	</div>
	<div class="form-group col-md-12">
	<%= f.label :zip_code, "Code Postal" %> : <%= f.text_field :zip_code, autofocus: true %><br/>
	---<br/>
	</div>
	<div class="form-group col-md-12">
	<%= f.label :contact, "Nom du contact" %> : <%= f.text_field :contact, autofocus: true %><br/>
	</div>
	<div class="form-group col-md-12">
	<%= f.label :phone_number, "Numéro de téléphone" %> : <%= f.telephone_field :phone_number, autofocus: true %><br/>
	</div>
	<div class="form-group col-md-12">
	<%= f.label :email, "Adresse mail" %> : <%= f.email_field :email, autofocus: true %><br/>
	</div>

	<%= f.submit "Modifier",class: 'btn btn-default' %>
	<%= render partial: "return_link" %>
<% end %>

</div>
</div>

Plante/app/views/admin/schools/index.html.erb
<div class="row center-row">
	<div class="col-md-12">
		<h1> Liste des Écoles </h1>
		<table class="table table-stripped table-bordered table-hover white-back">
		<thead>
			<th> ID </th>
			<th> Nom </th>
			<th> Ville </th>
			<th> CP </th>
			<th colspan='3'> Actions </th>
		</thead>
		<tbody>
			<% unless @all_schools.blank? %>
				<% @all_schools.each do |t| %>
					<tr>
						<td>
							<%= t.id.to_s %>
						</td>
						<td>
							<%= t.name.to_s %>
						</td>
						<td>
							<%= t.town.to_s %>
						</td>
						<td>
							<%= t.zip_code.to_s %>
						</td>
						<td>
										<%= link_to "Voir", admin_school_path(t) %>
						</td>
						<td>
										<%= button_to "Supprimer", admin_school_path(t), method: :delete,  data: {confirm: "Êtes-vous sûre ?"},class: 'btn btn-warning' %>
						</td>
						<td>
							<%= link_to "Accéder à la page de l'école", show_current_state_pages_path(id: t.id) %>
						</td>
					</tr>
				<% end %>
			<% else %>
				<tr>
					<td colspan='4'>
						Aucune école de disponible
					</td>
				</tr>
			<% end %>
		</tbody>
		</table>

		<%= link_to "Ajouter une école", new_admin_school_path %>
	</div>
</div>

Plante/app/views/admin/schools/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 transparent-co" style="text-align: center">
<h1> Ajout d'une nouvelle école </h1>

<%= form_for @school, url: "create", method: :post do |f| %>
	<div class="form-group col-md-12">
		<%= f.label :name, "Nom de l'école", :class => "scol-sm-2 control-label" %> : <%= f.text_field :name, autofocus: true %><br/>
		---<br/>
		</div>
		<div class="form-group col-md-12">
		<%= f.label :adress, "Adresse", :class => "scol-sm-2 control-label" %> : <%= f.text_field :adress, autofocus: true %><br/>
		</div>
		<div class="form-group col-md-12">
		<%= f.label :town, "Ville", :class => "scol-sm-2 control-label" %> : <%= f.text_field :town, autoficus: true %><br/>
		</div>
		<div class="form-group col-md-12">
		<%= f.label :zip_code, "Code Postal", :class => "scol-sm-2 control-label" %> : <%= f.text_field :zip_code, autofocus: true %><br/>
		---<br/>
		</div>
		<div class="form-group col-md-12">
		<%= f.label :contact, "Nom du contact" %> : <%= f.text_field :contact, autofocus: true %><br/>
		</div>
		<div class="form-group col-md-12">
		<%= f.label :phone_number, "Numéro de téléphone" %> : <%= f.telephone_field :phone_number, autofocus: true %><br/>
		</div>
		<div class="form-group col-md-12">
		<%= f.label :email, "Adresse mail" %> : <%= f.email_field :email, autofocus: true %><br/>
		</div>

		<%= f.submit "Créer",class: 'btn btn-default' %>
		<%= render partial: "return_link" %>
	</div>
<% end %>


</div>
</div>

Plante/app/views/admin/schools/show.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 transparent-co" style="text-align: center">
<h1> École : <%= @school.name %> </h1>

<b>Informations générales :</b><br/>
<br/>
Nom : <%= @school.name %><br/>
-----<br/>
Adresse : <%= @school.adress %><br/>
Ville : <%= @school.town %><br/>
Code Postal : <%= @school.zip_code %><br/>
-----<br/>
Nom du contact : <%= @school.contact %><br/>
Numéro de téléphone : <%= @school.phone_number %><br/>
Adresse mail : <%= @school.email %><br/>
-----<br/>
<b>Carte de commande liée :</b><br/>
<% unless @control_card.blank? %>
	Id : <%= @control_card.id.to_s %><br/>
	Numéro de série : <%= @control_card.serial_nbr.to_s %><br/>
<% else %>
	Aucune
<% end %>
<br/><br/>
 
<%= link_to "modifier", edit_admin_school_path, class: 'btn btn-default' %>

<%= render partial: "return_link"  %>
</div>
</div>