Plante/config/routes.rb
Rails.application.routes.draw do
  namespace :teacher do
  get 'media_file_handlers/index'
  end

  namespace :teacher do
  get 'media_file_handlers/new'
  end

  namespace :teacher do
  get 'media_file_handlers/create'
  end

  namespace :teacher do
  get 'media_file_handlers/destroy'
  end

  get 'media_file_handlers/index'

  get 'media_file_handlers/new'

  get 'media_file_handlers/create'

  get 'media_file_handlers/destroy'

  devise_for :users

   root 'pages#index'

     resources :pages do 
				get 'show_current_state', on: :collection
				get 'show_parameters', on: :collection
				get 'show_data', on: :collection
				get 'show_data2', on: :collection
				get 'show_media_file', on: :collection
				patch 'update_parameters', on: :collection
		 end
		
		 resources :tests do
		 end	 

    namespace :admin do
      resources :schools do 
		 	get 'index', on: :collection
		 	post 'create', on: :collection
		  end

		  resources :control_cards do
		  end

		  resources :data_cards do
		  end

		  resources :greenhouses do
		  end
    end

		namespace :teacher do
			resources :supervisions do
			end

			resources :media_file_handlers do
			end
		end

  

end

Plante/app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

Plante/app/models/control_card.rb
class ControlCard < ActiveRecord::Base
belongs_to :school
has_many :data_card
has_many :user
has_and_belongs_to_many :media_file
end

Plante/app/models/data_card.rb
class DataCard < ActiveRecord::Base
	belongs_to :control_card
	belongs_to :greenhouse
	has_many :value
end

Plante/app/models/greenhouse.rb
class Greenhouse < ActiveRecord::Base
	belongs_to :school
	has_many :data_card
	has_many :target_value
end

Plante/app/models/http_connection_log.rb
class HttpConnectionLog < ActiveRecord::Base
end

Plante/app/models/media_file.rb
class MediaFile < ActiveRecord::Base
	belongs_to :user
	belongs_to :media_file_type
	has_and_belongs_to_many :control_card #Ne sert a rien
	has_and_belongs_to_many :school

	mount_uploader :attachement
end

Plante/app/models/media_file_type.rb
class MediaFileType < ActiveRecord::Base
	has_many :media_file
end

Plante/app/models/school.rb
class School < ActiveRecord::Base
has_one :control_card
has_many :user
has_many :greenhouse
has_and_belongs_to_many :media_file
end

Plante/app/models/target_value.rb
class TargetValue < ActiveRecord::Base
	belongs_to :user
	belongs_to :value_type
	belongs_to :greenhouse
end

Plante/app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :school
	belongs_to :control_card
	has_many :target_value
	has_many :file
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

	def self.super_admin?
		return self.super_admin
	end

	def self.teacher?
		return self.teacher
	end
end

Plante/app/models/value.rb
class Value < ActiveRecord::Base
	belongs_to :value_type
	belongs_to :data_card
end

Plante/app/models/value_type.rb
class ValueType < ActiveRecord::Base
	has_many :target_value
	has_many :value
end

Plante/app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
		content_for(:header){text.to_s}
	end

	def convert_date(date)
		return date.strftime("%d/%m/%Y %H:%M:%S").to_s
	end

	def convert_date_short(date)
		return date.strftime("%d/%m/%Y").to_s
	end

	def convert_date_js(date)
		month = date[-1..-2].to_i
		return "#{date[0..1]} #{FRENCH_MONTHS["#{month}"]}"
	end

	def print_value(value, name)
		value ||= 'NA'
		return "#{value} #{VALUE_TYPES[:"#{name}"][2]}"
	end

	def print_value_name(name)
		case I18n.locale.to_s
			when "fr"
				return "#{VALUE_TYPES[:"#{name}"][0]}"
			when "en"
				return "#{VALUE_TYPES_EN[:"#{name}"][0]}"
		end
	end

	def print_unit(name)
		return "#{VALUE_TYPES[:"#{name}"][2]}"
	end

end

Plante/app/helpers/data_cards_helper.rb
module DataCardsHelper
end

Plante/app/helpers/media_files_helper.rb
module MediaFilesHelper
end

Plante/app/helpers/pages_helper.rb
module PagesHelper
	
end

Plante/app/helpers/tests_helper.rb
module TestsHelper
end

Plante/app/helpers/users_helper.rb
module UsersHelper
end

Plante/app/helpers/value_types_helper.rb
module ValueTypesHelper
end

Plante/app/helpers/values_helper.rb
module ValuesHelper
end

Plante/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puissance3 - Admin</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag  'welcomes', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>

<div class="container">

				<%= render "shared/navbar_admin" %>
		<% if !flash[:notice].blank? %>
			<div class = "alert alert-info alert-dismissible fade in">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<%= flash[:notice] %>
			</div>
		<% end %>
	</div>

	<%= yield :top_content %>

	<div class="container">
		<h1><%= yield :header %></h1>
	  <%= yield %>
	</div

</body>
</html>

Plante/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <head>
  <title>Puissance3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag  'welcomes', media: 'all', 'data-turbolinks-track' => true %>
  
</head>
<body <% if !user_signed_in? %> <% end %> >


	<div class="container nav_section">

		<%= render "shared/navbar" %>
		<br/><br/>
		<% if !flash[:notice].blank? %>
			<div class = "alert alert-info alert-dismissible fade in">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<%= flash[:notice] %>
			</div>
		<% end %>
	</div>

	<%= yield :top_content %>

	<div class="container">
	  <%= yield %>
	</div>

</body>
</html>

Plante/app/views/layouts/welcome_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCulture - Welcome</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag  'welcomes', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>
<%= yield %>
</body>
</html>

Plante/app/views/pages/_connected_index.html.erb
<span>Co</span>

Plante/app/views/pages/_nav_greenhouse.html.erb
<b><%= t('pages.chooseserre') %></b><br/><br/>

<ul class="nav nav-tabs ">
	<% @greenhouses.each do |y| %>			
		<li class="nav-item <%= "active" if @selected_greenhouse.id == y.id %>">
		<%= link_to "#{y.serial_nbr}", params.merge(id: params[:id], selected_greenhouse: y.id) %>
		</li>
	<% end %>
</ul>

Plante/app/views/pages/_sd_chart.html.erb
<div style="padding-top:15%;">
<div style="width:100%;height:450px;margin-bottom: 20%;">
	<div id="chart">
	</div>
	
	<% @value_types.collect(&:name).each do |v|%>

		<div id="<%= v %>-value" data-source="<%= instance_variable_get("@#{v}_values").collect{|y| y.value}.join('!') %>"></div>
		<div id="<%= v %>-date" data-source="<%= instance_variable_get("@#{v}_values").collect{|y| y.created_at.iso8601}.join('!') %>"></div>
	<% end %>
	
	<% date = @date %>
	<% array_date = ['xaxis'] %>
	<% while date < @date2 %>
		<% array_date << date.iso8601 %>
		<% if params[:day] != "" %>
			<% date = date + 2.hours %>
		<% elsif params[:month] != "" %>
			<% date = date + 1.days %>
		<% else %>
			<% date = date + 1.months %>
		<% end %>
	<% end %>

	<div id="xaxis" data-source="<%= "#{array_date.join('!')} "%>"></div>
	<div id="dummyvalue" data-source="<%="#{(["dummy"] + (1..(array_date.count - 1)).step(1).to_a).join('!')}"%>"></div>	
</div>

<b>Liste des valeurs pour chaque types<b><br/><br/>
<% @value_types.each do |y| %>
		<b> <%= VALUE_TYPES[:"#{y.name}"][0] %> </b>
		<table class='table table-hover table-bordered white-back'>
			<thead>
				<tr style="background-color:white;">
					<th> ID </th>
					<th> DataCard ID </th>
					<th> Date </th>
					<th> Valeur </th>
					<th> Valeur cible du moment </th>
				</tr>
			</thead>
			<tbody>
				<% instance_variable_get("@#{y.name}_values").each do |k,v| %>
						<tr>
								<td>
										<%= k.id %>
								</td>
								<td>
										<%= k.data_card_id %>
								</td>
								<td>
										<%= convert_date(k.created_at) %>
								</td>
								<td>
										<%= print_value(k.value,y.name) %>
								</td>
								<td>
										<%= print_value(@hash_target_values[:"id#{k.id}"], y.name) %>
								</td>
						</tr>
				<% end %>
		</tbody>
	</table>
	<br/>	
<% end %>
</div>

Plante/app/views/pages/_sd_timelapse.html.erb
<div class="row" style="margin-top: 17%;">
<div class="content-galleria">
	<% @all_pics.each do |v| %>

				<div class="pic" id="<%= v.path %>-description" data-source="<%=  v.description  %>"></div>
				
<% end %>

	<div id="galleria">
		<% @all_pics.each do |v| %>
		<%= link_to "#" ,class: "test" %>
		<div class="info"><div class="galleria-info2 "><%= v.description %></div></div>
			<%= image_tag "#{v.path}", :data => { :description => v.description }  %>
		<% end %>
	</div>
</div>
</div>


<%= javascript_include_tag "galleria-1.4.2.min.js" %>
<%= javascript_include_tag "galleria.twelve.min.js" %>

Plante/app/views/pages/index.html.erb
<% content_for :top_content do %>
	
    <div class="container nonco_hp">
		<% if user_signed_in? %>
			<%= render partial: "connected_index" %>
			<%= render partial: "actual_situation" %>
		<% else %>
			<%= render partial: "non_connected_index" %>
		<%end%>
    </div>
 
<% end %>

Plante/app/views/pages/show.html.erb
<h1> SHOW de PAGES </h1>

<b>Liste des serres disponibles</b><br/>
<% unless @greenhouses.blank? %>
<ol>
	<% @greenhouses.each do |y| %>
					<li><%= y.id %> --- <% if @selected_greenhouse.id == y.id %> Serre actuellement selectionnée <% else %> <%= link_to "Choisir cette serre", page_path(params[:id], selected_greenhouse: y.id) %><% end %></li>
<% end %>
</ol>
<% else %>
	Aucune serre n'est associée à cette école <br/>
<% end %>

<br/>
<br/>
<b>Liste des tyes de valeurs disponibles</b><br/>
<% unless @all_value_types.blank? %>
	<ol>
		<% @all_value_types.each do |t| %>
				<li>
					<%= t.id %> --- <%= t.name %>
				</li>
		<% end %>
<% else %>
	Aucun "value_type" trouvé <br/><br/>
<% end %>
<%= link_to "Ancienne page d'accueil connecté", root_path(all_display: true) %>

Plante/app/views/pages/show_current_state.html.erb
<div class="row center-row" style="margin-top:11%">
	<div class="col-md-12">

<%= render "actual_situation" %>

<%= render "nav_greenhouse" %>

<h1> Etat actuel de la serre </h1>

<b>Liste des dernières valeurs</b><br/>
	<table class='table table table-hover table-bordered white-back'>
		<thead>
			<% @value_types_header.each do |v| %>
				<th><%="#{v}"%></th>
			<% end %>
		</thead>
		<tbody>
			<% @value_types.each do |y| %>
					<tr>
							<td>
									<%= print_value_name(y.name) %> 
							</td>
							<td>
									<%= print_value(instance_variable_get("@#{y.name}_values"), y.name) %>
							</td>
							<td>
									<%= print_value(instance_variable_get("@target_#{y.name}"), y.name) %>
							</td>
					</tr>
			<% end %>
		</tbody>
	</table>


<%= link_to "Ancienne page d'accueil connecté", root_path(ana_display: "true", id: params[:id]) %>
</div>
</div>

Plante/app/views/pages/show_data.html.erb
<div class="row center-row" style="margin-top:11%">
	<div class="col-md-12">

		<%= render "nav_greenhouse" %>
		<br/>
		<!-- ############################################################## GESTION DU TRI DES DONNEES PAR DATES ######################################################################################## -->



		<div class="row">
			<div class="col-md-2" style="padding-left: 0px;">
				<ul class="nav nav-pills nav-stacked">
					<li>
						<%= link_to url_for(params.merge({type: "chart"})), class:"btn btn-default #{"active" if params[:type] == "chart"}" do %>
							<span class="glyphicon glyphicon-signal" aria-hidden="true"></span> <b>Graphe d'évolution</b>
						<% end %>
					</li>
					<li>
					<li>
						<%= link_to url_for(params.merge({type: "timelapse"})), class:"btn btn-default #{"active" if params[:type] == "timelapse"}" do %>
							<span class="glyphicon glyphicon-camera" aria-hidden="true"></span> <b>Timelapse</b>
						<% end %>
					</li>
				</ul>
			</div>
			<div class="col-md-2">
				<div class="btn-group btn-justified" role="group" aria-label="...">
					<b>Choisir une année :</b><br/>
						<% for i in @start_year..@end_year %>
									<% if params[:year].to_i == i %>
										<%= link_to i.to_s, url_for(params.merge({year: "", month: "", day: ""})), class:"btn btn-default #{"active" if i == params[:year].to_i}" %>
									<% else %>
										<%= link_to i.to_s, url_for(params.merge({year: i.to_s})), class:"btn btn-default #{"active" if i == params[:year].to_i}" %>				
									<% end %>
						<% end %>
				</div>
			</div>
			<div class="col-md-4">
				<div class="btn-group btn-justified" role="group" aria-label="...">
					<b>Choisir un mois :</b><br/>
						<div style="visibility:<%= @display_div_months %>">
							<% for i in 1..@nb_months %>
								<% if params[:month].to_i == i %>
									<%= link_to FRENCH_MONTHS["#{i}"], url_for(params.merge({month: "", day: ""})), class:"btn btn-default mois #{"active" if i == params[:month].to_i}" %>	
								<% else %>
									<%= link_to FRENCH_MONTHS["#{i}"], url_for(params.merge({month: i.to_s})), class:"btn btn-default mois #{"active" if i == params[:month].to_i}" %>
								<% end %>
								<% if i%4 == 0 %><% end %>
							<% end %>
						</div>
						<br/>
					</div>
				</div>
				<div class="col-md-3">
					<div class="btn-group btn-justified" role="group" aria-label="...">
						<b>Choisir un jour :</b><br/>
							<div style="visibility:<%= @display_div_days %>">
								<% for i in 1..@days_in_month %>
									<% if params[:day].split('!').include?(i.to_s) %>
												<% array_day = params[:day].split('!') %>
												<% array_day.delete(i.to_s)%>
		
												<% if array_day == [] %>
																<% param = "" %>
												<% else %>
																<% param = array_day.join('!') %>
												<% end %>
		
									<% else %>
												<% param = params[:day].split('!').push(i.to_s).join('!') %>
									<% end %>
		
									<% if params[:day].blank? || ([i, (i - 1), (i + 1)].any?{|x| params[:day].split('!').map(&:to_i).include?(x)} && ![i, (i - 1), (i + 1)].all?{|x| params[:day].split('!').map(&:to_i).include?(x)})%>
												<% disabled = "" %>
									<% else %>
												<% disabled = "disabled" %>
									<% end %>
		
									<% i < 10 ? i_to_show = "0" + i.to_s : i_to_show = i.to_s %>

									<% if params[:day].split('!').map(&:to_i).include?(i) %>
										<% active = "active" %>
									<% else %>
										<% active = "" %>
									<% end %>

									<% if disabled == "disabled" && active == "active" %>
										<% disabled = "disabled2" %>
									<% end %>

									<%= link_to i_to_show, url_for(params.merge({day: param})), class:"btn btn-default #{disabled ||= ""} #{active}"  %>
									
									<% if i%5 == 0 %><br/><% end %>
								<% end %>
							</div>
							<br/>
						</div>
					</div>
					<div class="col-md-1">
						<%= link_to "Remise à zéro", url_for(params.merge({day: "", month: "", year: ""})), class: "btn btn-default" %>
					</div>
				</div>
			</div>
		<!-- ######################################################################################################################################################### -->
		<%= render partial: "sd_#{params[:type]}" %>
	</div>
</div>
<br/>
<br/>




<%= javascript_include_tag "data_show2.js" %>
<%= javascript_include_tag "highcharts.js" %>
<%= javascript_include_tag "exporting.js" %>

Plante/app/views/pages/show_media_file.html.erb
<div class="row center-row" style="margin-top:9%">
	<div class="col-md-12">
<h1> Supports éducatifs </h1>
<br/><br/>

<b>Trier par type de fichiers:</b>
<div class="btn-group btn-group-justified" role="group"	aria-label="...">
	<%= link_to "Tous", show_media_file_pages_path(id: params[:id], search_type: "all"), class:"btn btn-default #{"active" if (params[:search_type] == "all" || params[:search_type].blank?)}" %>
	<% @media_file_types.each do |v| %>
		<%= link_to v.translated_name, show_media_file_pages_path(id: params[:id], search_type: v.name), class: "btn btn-default #{"active" if params[:search_type] == v.name}" %>
	<% end %>
</div>
<br/><br/>

<% @media_files.each do |media_file| %>
 <div class="well">
	<h3><%= media_file.title.capitalize %>&nbsp &nbsp<small>Ajouté le <%= convert_date_short(media_file.created_at) %></small></h3	>

	<table class="table table-condensed">
		<tr>
			<td class="col-md-6">
				<h4>Description :</h4>
				<%= media_file.description %>
			</td>
			<td class="col-md-6">
				<h4> Télécharger <i><%= media_file.attachement.to_s.split('/')[-1] %></i> :</h4>
				<%= link_to media_file.attachement_url, class: "btn btn-primary" do %>
					<span class="glyphicon glyphicon-save" aria-hidden="true"></span> Télécharger
				<% end %>
			</td>
		</tr>
	</table>
 </div>
<% end %>
</div>
</div>

Plante/app/views/pages/show_parameters.html.erb
<div class="row center-row" style="margin-top:11%">
	<div class="col-md-12">

					<%= render "nav_greenhouse" %>


<table class="table table-stripped white-back">
	<thead>
		<th> <%= t('pages.valuetype')  %><!--Type de valeur--> </th>
		<th> <%= t('pages.value')  %></th>
		<th> <%= t('pages.actions')  %> </th>
	</thead>
	<tbody>
	<% if current_user.teacher? %>
		<% @value_types.each do |y| %>
			<tr>
				<%= form_for y, url: update_parameters_pages_path, method: :patch do |f| %>
					<td> <%= print_value_name(y.name) %></td>
					<td> <%= number_field_tag "#{y.name}_value", instance_variable_get("@target_#{y.name}"), within: 1..50 %> <%=print_unit(y.name) %></td>
					<%= hidden_field_tag :greenhouse_id, @selected_greenhouse.id %>
					<%= hidden_field_tag :value_type_id, y.id %>
					<%= hidden_field_tag :school_id, params[:id] %>
					<td> <%= f.submit t('pages.modify')%></td>
				<% end %>
			</tr>
		<% end %>
	<% else %>
		<% @value_types.each do |y| %>
			<tr>
				<td> <%= print_value_name(y.name) %></td>
				<td> <%= print_value(instance_variable_get("@target_#{y.name}"),y.name) %></td>
			</tr>
		<% end %>
	<% end %>
</tbody>
</table>


</div>
</div>

Plante/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default ">
				<div class="navbar-header">
								<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
												<span class="sr-only">Toggle navigation</span>
												<span class="icon-bar"></span>
												<span class="icon-bar"></span>
												<span class="icon-bar"></span>
								</button>
								<a class="navbar-brand" href="#">
												<%= link_to image_tag("logo.png", alt: "Logo", id: "logo"), root_path, class: "btn"%>
								</a> 
				</div>

				<% if user_signed_in? %>
					<div id="navbar" class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-left">
							<li class="<%= "active" if request.env['PATH_INFO'] == show_current_state_pages_path %>"><%= link_to t('pages.actusituation'), show_current_state_pages_path(id: params[:id], selected_greenhouse: params[:selected_greenhouse]), class: "nav_btn" %></li>
							<li class="<%= "active" if request.env['PATH_INFO'] == show_parameters_pages_path %>"><%= link_to t('pages.changeparam'), show_parameters_pages_path(id: params[:id], selected_greenhouse: params[:selected_greenhouse]), class: "nav_btn"%></li>
							<li class="<%= "active" if request.env['PATH_INFO'] == show_data_pages_path %>"><%= link_to t('pages.evolution'), show_data_pages_path(id: params[:id], selected_greenhouse: params[:selected_greenhouse], year: "", month: "", day: "", type: "chart"), class:"nav_btn" %></li>
							<!--<li class="<%= "active" if request.env['PATH_INFO'] == show_data2_pages_path %>"><%= link_to "Évolution", show_data2_pages_path(id: params[:id], selected_greenhouse: params[:selected_greenhouse], year: "", month: "", day: ""), class:"nav_btn" %></li>-->
							<li class="<%= "active" if request.env['PATH_INFO'] == show_media_file_pages_path %>"><%= link_to t('pages.educsupport'), show_media_file_pages_path(id: params[:id]), class: "nav_btn" %></li>
							<% if current_user.super_admin? || current_user.teacher? %>
								<li class="dropdown <%= "active" if [edit_user_registration_path,teacher_supervisions_path,admin_schools_path].include?(request.env['PATH_INFO'])%>">
	      	    	  <a data-toggle="dropdown" class="dropdown-toggle" href="#"><%= t('pages.administration')%><b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li class="<%= "active" if request.env['PATH_INFO'] == edit_user_registration_path %>"><%= link_to t('pages.profilemanagement'), edit_user_registration_path, class: "nav_btn" %></li>
										<li class="<%= "active" if request.env['PATH_INFO'] == teacher_supervisions_path %>"><%= link_to t('pages.profarea'), teacher_supervisions_path(id: params[:id]), class: "nav_btn" %></li>
										<% if current_user.super_admin %>
											<li class="<%= "active" if request.env['PATH_INFO'] == admin_schools_path %>"> <%= link_to t('pages.adminarea'), admin_schools_path, class: "nav_btn" %></li>
										<% end %>
									</ul>
								</li>
							<% end %>
						</ul>
					</div><!--/.nav-collapse -->
				<% end %>

				<div class="col-md-3 col-md-offset-9" style="position: absolute;">
					<div class="language">
						
	
						<%= link_to url_for(params.merge({locale:"en"})) do %>
						 <%= image_tag 'enflag.png', alt: 'England flag', class: "flag" %>
						<% end %>
						<%= link_to url_for(params.merge({locale:"fr"})) do %>
						 <%= image_tag 'frflag.png', alt: 'French flag', class: "flag"%>
						<% end %>


						
					</div>
					<div class="user_info" >
						<% if user_signed_in? %>
										<p style="margin-top:-42%;"><%= t('pages.hello')%> <%= current_user.first_name%> <%= current_user.last_name%></p>
										<p style="margin-top:-42%;"><%= link_to t('pages.logout'), destroy_user_session_path %></p>
						<% else %>      
										<!-- Je sais c'est pas bien mais je le fais a l'arrache dans le train pour y avoir accès :) -->
										<p style="position:relative;"><%= link_to 'Se connecter', new_user_session_path, class: "btn btn_style_connect" %></p>

						<% end %>
					</div>
				</div>


</nav>

Plante/app/views/shared/_navbar_admin.html.erb
<nav class="navbar navbar-default ">
				<div class="navbar-header">
								<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
												<span class="sr-only">Toggle navigation</span>
												<span class="icon-bar"></span>
												<span class="icon-bar"></span>
												<span class="icon-bar"></span>
								</button>
								<a class="navbar-brand" href="#">
												<%=image_tag("logo.png", alt: "Logo", id: "logo")%>
								</a>
				</div>

				<% if user_signed_in? %>
					<div id="navbar" class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-left">
							<li class="<%= "active" if request.env['PATH_INFO'] == admin_schools_path %>"><%= link_to "Gestion des Écoles", admin_schools_path, class: "nav_btn" %></li>
							<li class="<%= "active" if request.env['PATH_INFO'] == admin_greenhouses_path %>"><%= link_to "Gestion des Serres", admin_greenhouses_path, class: "nav_btn"%></li>
							<li class="<%= "active" if request.env['PATH_INFO'] == admin_control_cards_path %>"><%= link_to "Gestion des cartes principales", admin_control_cards_path, class:"nav_btn" %></li>
							<li class="<%= "active" if request.env['PATH_INFO'] == admin_data_cards_path %>"><%= link_to "Gestion des cartes secondaires", admin_data_cards_path, class: "nav_btn" %></li>
						</ul>
					</div><!--/.nav-collapse -->
				<% end %>

				<div class="col-md-3 col-md-offset-9" style="margin-top: -4%">
					<div class="user_info">
						<% if user_signed_in? %>
										<p>Bonjour <%= current_user.first_name%> <%= current_user.last_name%></p>
										<p><%= link_to 'Se déconnecter', destroy_user_session_path %></p>
						<% end %>
					</div>
				</div>


</nav>