Plante/config/routes.rb
Rails.application.routes.draw do
  namespace :teacher do
  get 'media_file_handlers/index'
  end

  namespace :teacher do
  get 'media_file_handlers/new'
  end

  namespace :teacher do
  get 'media_file_handlers/create'
  end

  namespace :teacher do
  get 'media_file_handlers/destroy'
  end

  get 'media_file_handlers/index'

  get 'media_file_handlers/new'

  get 'media_file_handlers/create'

  get 'media_file_handlers/destroy'

  devise_for :users

   root 'pages#index'

     resources :pages do 
				get 'show_current_state', on: :collection
				get 'show_parameters', on: :collection
				get 'show_data', on: :collection
				get 'show_data2', on: :collection
				get 'show_media_file', on: :collection
				patch 'update_parameters', on: :collection
		 end
		
		 resources :tests do
		 end	 

    namespace :admin do
      resources :schools do 
		 	get 'index', on: :collection
		 	post 'create', on: :collection
		  end

		  resources :control_cards do
		  end

		  resources :data_cards do
		  end

		  resources :greenhouses do
		  end
    end

		namespace :teacher do
			resources :supervisions do
			end

			resources :media_file_handlers do
			end
		end

  

end

Plante/app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

Plante/app/models/control_card.rb
class ControlCard < ActiveRecord::Base
belongs_to :school
has_many :data_card
has_many :user
has_and_belongs_to_many :media_file
end

Plante/app/models/data_card.rb
class DataCard < ActiveRecord::Base
	belongs_to :control_card
	belongs_to :greenhouse
	has_many :value
end

Plante/app/models/greenhouse.rb
class Greenhouse < ActiveRecord::Base
	belongs_to :school
	has_many :data_card
	has_many :target_value
end

Plante/app/models/http_connection_log.rb
class HttpConnectionLog < ActiveRecord::Base
end

Plante/app/models/media_file.rb
class MediaFile < ActiveRecord::Base
	belongs_to :user
	belongs_to :media_file_type
	has_and_belongs_to_many :control_card #Ne sert a rien
	has_and_belongs_to_many :school

	mount_uploader :attachement
end

Plante/app/models/media_file_type.rb
class MediaFileType < ActiveRecord::Base
	has_many :media_file
end

Plante/app/models/school.rb
class School < ActiveRecord::Base
has_one :control_card
has_many :user
has_many :greenhouse
has_and_belongs_to_many :media_file
end

Plante/app/models/target_value.rb
class TargetValue < ActiveRecord::Base
	belongs_to :user
	belongs_to :value_type
	belongs_to :greenhouse
end

Plante/app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :school
	belongs_to :control_card
	has_many :target_value
	has_many :file
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

	def self.super_admin?
		return self.super_admin
	end

	def self.teacher?
		return self.teacher
	end
end

Plante/app/models/value.rb
class Value < ActiveRecord::Base
	belongs_to :value_type
	belongs_to :data_card
end

Plante/app/models/value_type.rb
class ValueType < ActiveRecord::Base
	has_many :target_value
	has_many :value
end

Plante/app/controllers/teacher/media_file_handlers_controller.rb
class Teacher::MediaFileHandlersController < ApplicationController
  def index
		@media_file_types = MediaFileType.all
		if params[:search_type].blank? || params[:search_type] == "all"
			@media_files = MediaFile.all.select{|v| v.school.collect(&:id).include?(params[:id].to_i)}.sort{|a,b| a.attachement.to_s.split('/')[-1] <=> b.attachement.to_s.split('/')[-1]}
		end

		@media_file_types.each do |v|
			if params[:search_type] == v.name  
				@media_files = MediaFile.where("media_file_type_id = ?", v.id).select{|v| v.school.collect(&:id).include?(params[:id].to_i)}.sort{|a,b| a.attachement.to_s.split('/')[-1] <=> b.attachement.to_s.split('/')[-1]}
				break
			end
		end
  end

  def new
		@media_file = MediaFile.new
  end

  def create
		media_file = MediaFile.new(media_file_params)
		school = School.find(params[:school_id])
		media_file.school << school

		if media_file.save
			redirect_to teacher_media_file_handlers_path(id: params[:school_id]), notice: "Ajout effectué"
		else
			render "new"
		end
  end

	def edit
		@media_file = MediaFile.find(params[:id])
	end

	def update
		media_file = MediaFile.find(params[:id])
		if media_file.update_attributes(media_file_params)
			redirect_to teacher_media_file_handlers_path(id: params[:school_id]), notice: "Mise à jour effectuée"
		else
			render 'edit'
		end
	end

  def destroy
		media_file = MediaFile.find(params[:id])
		media_file.destroy
		redirect_to teacher_media_file_handlers_path(id: params[:school_id]), notice: "Suppression effectuée"
  end

	private

	def media_file_params
		params.require(:media_file).permit(:title, :description, :attachement, :to_show, :media_file_type_id)
	end
end

Plante/app/controllers/teacher/supervisions_controller.rb
class Teacher::SupervisionsController < ApplicationController
	before_filter :verify_authorization

	def index
		all_operations = HTTP_CONNECTION_TYPES.keys
		@all_families = HTTP_CONNECTION_TYPES.values.collect{|g| g[1]}.uniq
		@all_greenhouses = Greenhouse.where("school_id = ?", params[:id])
		
		##### VALUE TYPES
		value_types = ValueType.all
		@all_value_types = Hash.new
		value_types.each do |v|
			@all_value_types[:"#{v.id}"] = v.name
		end
		
		
		##### HTTP LOGS
		@logs = Hash.new
		@all_greenhouses.each do |t|
			@logs[:"#{t.serial_nbr}"] = Hash.new
			all_operations.each do |v|
				log = HttpConnectionLog.where("connection_type = ? AND greenhouse_id = ?", v.to_s, t.id)
	
				unless log.blank?
					log = log.reverse.first.created_at.localtime.strftime("%d/%m/%Y %H:%M:%S")
					@logs[:"#{t.serial_nbr}"].merge!({"#{v}": log})
				else
					@logs[:"#{t.serial_nbr}"].merge!({"#{v}": ""})
				end
			end
		end
		
		##### TARGET VALUES
		@all_target_values = Array.new
		req = TargetValue.where("greenhouse_id IN (?) AND active = ?", @all_greenhouses.collect(&:id), true)
		req.each do |k|
			@all_target_values << [k.value_type_id,k.value]
		end
	end

private

	def verify_authorization
		if current_user.super_admin?
			return true
		end

		if current_user.school.id != params[:id] || !current_user.teacher?
			raise
		end
	end

end

Plante/app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
		content_for(:header){text.to_s}
	end

	def convert_date(date)
		return date.strftime("%d/%m/%Y %H:%M:%S").to_s
	end

	def convert_date_short(date)
		return date.strftime("%d/%m/%Y").to_s
	end

	def convert_date_js(date)
		month = date[-1..-2].to_i
		return "#{date[0..1]} #{FRENCH_MONTHS["#{month}"]}"
	end

	def print_value(value, name)
		value ||= 'NA'
		return "#{value} #{VALUE_TYPES[:"#{name}"][2]}"
	end

	def print_value_name(name)
		case I18n.locale.to_s
			when "fr"
				return "#{VALUE_TYPES[:"#{name}"][0]}"
			when "en"
				return "#{VALUE_TYPES_EN[:"#{name}"][0]}"
		end
	end

	def print_unit(name)
		return "#{VALUE_TYPES[:"#{name}"][2]}"
	end

end

Plante/app/helpers/data_cards_helper.rb
module DataCardsHelper
end

Plante/app/helpers/media_files_helper.rb
module MediaFilesHelper
end

Plante/app/helpers/pages_helper.rb
module PagesHelper
	
end

Plante/app/helpers/teacher/media_file_handlers_helper.rb
module Teacher::MediaFileHandlersHelper
end

Plante/app/helpers/teacher/supervisions_helper.rb
module Teacher::SupervisionsHelper
end

Plante/app/helpers/tests_helper.rb
module TestsHelper
end

Plante/app/helpers/users_helper.rb
module UsersHelper
end

Plante/app/helpers/value_types_helper.rb
module ValueTypesHelper
end

Plante/app/helpers/values_helper.rb
module ValuesHelper
end

Plante/app/views/teacher/_nav.html.erb
<span class="col-md-5"></span><h1> Zone Professeur </h1>
<br/><br/>
<ul class="nav nav-tabs">
	<li class="nav-item <%= "active" if request.env['PATH_INFO'] == teacher_supervisions_path %>">
		<%= link_to "Vision Générale", teacher_supervisions_path(id: params[:id]) %>
	</li>
	<li class="nav-item <%= "active" if request.env['PATH_INFO'] == teacher_media_file_handlers_path %>">
		<%= link_to "Fichiers sur le serveur", teacher_media_file_handlers_path(id: params[:id]) %>
	</li>
</ul>

Plante/app/views/teacher/media_file_handlers/create.html.erb
<div class="row center-row" style="margin-top:9%">
	<div class="col-md-12">
<h1>Teacher::MediaFileHandlers#create</h1>
<p>Find me in app/views/teacher/media_file_handlers/create.html.erb</p>
</div>
</div>

Plante/app/views/teacher/media_file_handlers/destroy.html.erb
<div class="row center-row" style="margin-top:9%">
	<div class="col-md-12">
<h1>Teacher::MediaFileHandlers#destroy</h1>
<p>Find me in app/views/teacher/media_file_handlers/destroy.html.erb</p>
</div>
</div>

Plante/app/views/teacher/media_file_handlers/edit.html.erb
<div class="row center-row" style="margin-top:9%">
	<div class="col-md-12">
<% if !@media_file.errors.empty? %>
  <div class = "alert alert-error">
      
		<ul>
			<% @media_file.errors.full_messages.each do |msg| %>
			  <li><%= msg %></li>
			<% end %>
		</ul>
					       
	</div>
<% end %>


<div class = "well">
	<h1> Mise à jour des informations </h1><br/><br/>
	<%= form_for @media_file, url: teacher_media_file_handler_path, method: :PUT, html: { multipart: true } do |f| %>
					<%= hidden_field_tag :school_id, params[:school_id] %>
					<%= f.label :title, "Titre :", :class => "col-md-3" %><%= f.text_field :title, :class => "col-md-3" %><br/><br/>
					<%= f.label :description, "Description :", :class => "col-md-3" %><%= f.text_area :description, :class => "col-md-3" %><br/><br><br/><br/>
					<%= f.label :type, "Type de fichier :", :class => "col-md-3" %><%= f.select :media_file_type_id, MediaFileType.all.collect{|t| [t.translated_name,t.id]}, {:prompt => "-- choisir un type de fichier --"},:class => "col-md-3" %><br/><br/><br/>
					<%= f.label :to_show, "À afficher dans la partie élève ?", :class => "col-md-3" %><%= f.select :to_show, [["NON",false],["OUI",true]] %><br/><br>
					<strong class="col-md-3">Fichier stocké : </strong> <%= @media_file.attachement.to_s.split('/')[-1] %> <br/><br/>
					<%= f.submit "Enregistrer", class: "btn btn-primary" %>
	<% end %>
</div>
</div>
</div>

Plante/app/views/teacher/media_file_handlers/index.html.erb
<div class="row center-row" style="margin-top:9%">
	<div class="col-md-12">

<%= render :partial => "teacher/nav" %>
<br/><br/>
<%= link_to "Nouveau fichier", new_teacher_media_file_handler_path(school_id: params[:id]), class: "btn btn-primary" %>
<br />
<br />

<b>Trier par type de fichiers:</b>
<div class="btn-group btn-group-justified" role="group"	aria-label="...">
	<%= link_to "Tous", teacher_media_file_handlers_path(id: params[:id], search_type: "all"), class:"btn btn-default #{"active" if (params[:search_type] == "all" || params[:search_type].blank?)}" %>
	<% @media_file_types.each do |v| %>
		<%= link_to v.translated_name, teacher_media_file_handlers_path(id: params[:id], search_type: v.name), class: "btn btn-default #{"active" if params[:search_type] == v.name}" %>
	<% end %>
</div>

<br/>

<table class = "table table-bordered table-striped">
	<thead>
	  <tr>
			<th width=40%>Titre</th>
			<th width=25%>Nom du fichier</th>
			<th width=15%>Type</th>
			<th width=5%>Actif</th>
	    <th width=15% colspan="3">Actions</th>
		</tr>
	</thead>
	
	<tbody>
    <% @media_files.each do |media_file| %>
      <tr>
				<td><%= media_file.title %></td>
				<td><%= media_file.attachement.to_s.split('/')[-1] %></td>
				<td><%= media_file.media_file_type.translated_name %></td>
				<td><%= media_file.to_show == true ? "V" : "F" %></td>
				<td>
					<%= link_to media_file.attachement_url, class: "btn btn-primary" do %>
						<span class="glyphicon glyphicon-save" aria-hidden="true"></span>
					<% end %>
				</td>
				<td>
					<%= link_to edit_teacher_media_file_handler_path(id: media_file.id, school_id: params[:id]), class:"btn btn-warning" do %>
						<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
					<% end %>
				</td>
				<td>
					<%= button_to teacher_media_file_handler_path(id: media_file.id, school_id: params[:id]), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{media_file}?" do %>
						<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
					<% end %>
				</td>
			</tr>
							          
		<% end %>
	</tbody>
													   
</table>

</div>
</div>

Plante/app/views/teacher/media_file_handlers/new.html.erb
<div class="row center-row" style="margin-top:9%">
	<div class="col-md-12">
<% if !@media_file.errors.empty? %>
  <div class = "alert alert-error">
      
		<ul>
			<% @media_file.errors.full_messages.each do |msg| %>
			  <li><%= msg %></li>
			<% end %>
		</ul>
					       
	</div>
<% end %>


<div class = "well">
	<h1> Importer un nouveau fichier </h1><br/><br/>
	<%= form_for @media_file, url: teacher_media_file_handlers_path, html: { multipart: true } do |f| %>
					<%= hidden_field_tag :school_id, params[:school_id] %>
					<%= f.label :title, "Titre :", :class => "col-md-3" %><%= f.text_field :title, :class => "col-md-3" %><br/><br/>
					<%= f.label :description, "Description :", :class => "col-md-3" %><%= f.text_area :description, :class => "col-md-3" %><br/><br><br/><br/>
					<%= f.label :type, "Type de fichier :", :class => "col-md-3" %><%= f.select :media_file_type_id, MediaFileType.all.collect{|t| [t.translated_name,t.id]}, {:prompt => "-- choisir un type de fichier --"},:class => "col-md-3" %><br/><br/><br/>
					<%= f.label :to_show, "Afficher dans la partie élève ?", :class => "col-md-3" %><%= f.select :to_show, [["NON",false],["OUI",true]] %><br/><br/>
					<%= f.label :attachement, "Fichier à ajouter :", :class => "col-md-3" %><%= f.file_field :attachement, :class => "col-md-3" %><br/><br><br/><br/>
					<%= f.submit "Enregistrer", class: "btn btn-primary" %>
	<% end %>
</div>
</div>
</div>

Plante/app/views/teacher/supervisions/index.html.erb
<div class="row center-row" style="margin-top:9%">
	<div class="col-md-12">

<%= render :partial => "teacher/nav" %>

<h1> Synthèse de l'état des différentes serres </h1>
<br/>
<% @all_greenhouses.collect(&:serial_nbr).each do |v| %>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4><b>Serre "<%= v %>"</b></h4>
		</div>
		<div class="panel-body">
			<% @all_families.each do |family| %>
				<table class="table table-bordered table-striped table-hover">
					<tr>
						<th colspan='2'> <%= HTTP_CONNECTION_FAMILIES[:"#{family}"]%> </th>
						<% HTTP_CONNECTION_TYPES.each do |type,val| %>
							<% next if val[1] != family %>
							<% @logs[:"#{v}"].each do |c,j| %>
								<% next if c.to_s != type.to_s %>
								<% case family %>
									<% when "material" %>
										<% array_comp = ["available","disabled"] %>
										
										<% if array_comp.include?(c.to_s.split('_')[-1])%>
											<% if array_comp.all?{|comp| @logs[:"#{v}"][:"#{c.to_s.split('_')[0..-2].join('_')}_#{comp}"] == ""}%>
												<% if	c.to_s.split('_')[-1] == "available" %>
													<tr>
														<td><%= HTTP_CONNECTION_TYPES[:"#{c}"][0].capitalize %></td>
														<td class="warning"><b>Inconnu</b></span></td>
													</tr>
												<% end %>
												<% next %>
											<% end %>

											<% opposite = array_comp[array_comp.index(c.to_s.split('_')[-1]) - 1] %>
											<% other_data = @logs[:"#{v}"][:"#{c.to_s.split('_')[0..-2].join('_')}_#{opposite}"] %>
											<% next if other_data > j %>
											<tr>
												<td><%= HTTP_CONNECTION_TYPES[:"#{c}"][0].capitalize %></td>
												<td class="<%="danger" if c.to_s.split('_')[-1] == "disabled"%><%="success" if c.to_s.split('_')[-1] == "available"%>"><b><%=HTTP_CONNECTION_STATES[:"#{c.to_s.split('_')[-1]}"] %></b><br/> au <small><%= j %></small></span></td>
											</tr>
										<% end %>
									<% else %>
										<tr>
											<td><%= HTTP_CONNECTION_TYPES[:"#{c}"][0].capitalize %></td>
											<td><b><%= j %></b></td>
										</tr>
								<% end %>
							<% end %>
						<% end %>
		</tr>
		</table>
					<% end %>
		</div>
	</div>
<% end %>

</div>
</div>