Plante/config/routes.rb
Rails.application.routes.draw do
  namespace :teacher do
  get 'media_file_handlers/index'
  end

  namespace :teacher do
  get 'media_file_handlers/new'
  end

  namespace :teacher do
  get 'media_file_handlers/create'
  end

  namespace :teacher do
  get 'media_file_handlers/destroy'
  end

  get 'media_file_handlers/index'

  get 'media_file_handlers/new'

  get 'media_file_handlers/create'

  get 'media_file_handlers/destroy'

  devise_for :users

   root 'pages#index'

     resources :pages do 
				get 'show_current_state', on: :collection
				get 'show_parameters', on: :collection
				get 'show_data', on: :collection
				get 'show_data2', on: :collection
				get 'show_media_file', on: :collection
				patch 'update_parameters', on: :collection
		 end
		
		 resources :tests do
		 end	 

    namespace :admin do
      resources :schools do 
		 	get 'index', on: :collection
		 	post 'create', on: :collection
		  end

		  resources :control_cards do
		  end

		  resources :data_cards do
		  end

		  resources :greenhouses do
		  end
    end

		namespace :teacher do
			resources :supervisions do
			end

			resources :media_file_handlers do
			end
		end

  

end

Plante/app/models/control_card.rb
class ControlCard < ActiveRecord::Base
belongs_to :school
has_many :data_card
has_many :user
has_and_belongs_to_many :media_file
end

Plante/app/controllers/admin/control_cards_controller.rb
class Admin::ControlCardsController < ApplicationController
	layout "admin"

	def index
		@all_control_cards = ControlCard.all
	end

	def new
		@control_card = ControlCard.new
		@linkable_schools = School.all.select{|y| y.control_card.blank? == true}
	end

	def create
		@control_card = ControlCard.new(control_card_params)
		if @control_card.save
			flash[:notice] = "Nouvelle carte de contrôle ajoutée"
			redirect_to admin_control_card_path(@control_card)
		else
			flash[:notice] = "Erreur lors de l'enregistrement"
			render "new"
		end
	end

	def edit
		@control_card = ControlCard.where(id: params[:id])[0]
		@linkable_schools = School.all.select{|y| y.control_card.blank? == true}
		unless @control_card.school.blank?
			@linkable_schools << @control_card.school
		end
	end

	def update
		@control_card = ControlCard.where(id: params[:id].to_i)[0]
		if @control_card.update_attributes(control_card_params)
			flash[:notice] = "Mise à jour effectuée"
			redirect_to admin_control_card_path(@control_card)
		else
			flash[:notice] = "Erreur lors de la mis à jour"
			render "edit"
		end
	end

	def destroy
		@control_card = ControlCard.where(id: params[:id])[0]
		if @control_card.destroy
			flash[:notice] = "Carte de contrôle supprimée"
			redirect_to admin_control_cards_path
		else
			flash[:notice] = "Erreur lors de la suppression"
			redirect_to admin_control_cards_path
		end
	end

	def show
		@control_card = ControlCard.where(id: params[:id].to_i)[0]	
		unless @control_card.school.blank?
			@linked_school = School.where(id: @control_card.school.id)[0]
		end
	end

	private

	def control_card_params
		params.require(:control_card).permit(:serial_nbr, :school_id)
	end

end

Plante/app/controllers/control_cards_controller.rb
class ControlCardsController < ApplicationController
end

Plante/app/helpers/admin/control_cards_helper.rb
module Admin::ControlCardsHelper
end

Plante/app/helpers/control_cards_helper.rb
module ControlCardsHelper
end

Plante/app/views/admin/control_cards/_return_link.html.erb
<%= link_to "Retour", admin_control_cards_path, class: 'btn btn-default' %>

Plante/app/views/admin/control_cards/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 transparent-co" style="text-align: center">
<h1> Modification de la carte de commande : <%= @control_card.serial_nbr.to_s %> </h1>

<%= form_for @control_card, url: admin_control_card_path, method: :patch do |f| %>
<div class="form-group col-md-12">
	<%= f.label :serial_nbr, "Numéro de série" %> : <%= f.text_field :serial_nbr, autofocus: true, class: 'form-control '  %><br/>
</div>
<div class="form-group col-md-12">
	<%= f.label :school_id, "École liée" %> : <%= f.select :school_id, @linkable_schools.collect{|t| ["#{t.name} - #{t.town}", t.id]}, {prompt: "Choisir une école"} %> <br/>
</div>
	<%= f.submit "Modifier",class: 'btn btn-default' %>
	<%= render partial: "return_link" %>

<% end %>

</div>
</div>

Plante/app/views/admin/control_cards/index.html.erb
<div class="row center-row" >
	<div class="col-md-12">
<h1> Liste des cartes principales </h1>

<table class="table table-stripped table-hover table-bordered white-back">
	<thead>
		<th> ID  </th>
		<th> Numero de Série </th>
		<th> Liée à une école </th>
		<th colspan='2'> Actions </th>
	</thead>
	</tbody>
	<% @all_control_cards.each do |y| %>
		<tr>
				<td> 
						<%= y.id %>
				</td>
				<td>
						<%= y.serial_nbr %>
				</td>
				<td>
						<% unless y.school.blank? %>
								OUI
						<% else %>
								NON
						<% end %>
				</td>
				<td>
					<%= link_to "Voir", admin_control_card_path(y) %>
				</td>
				<td>
					<%= button_to "Supprimer", admin_control_card_path(y), method: :delete ,class: 'btn btn-warning' %>
				</td>
		</tr>
	<% end %>
</tbody>
</table>

<%= link_to "Ajouter une nouvelle carte principale", new_admin_control_card_path %>
</div>
</div>

Plante/app/views/admin/control_cards/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 transparent-co" style="text-align: center">
<h1> Ajout d'une nouvelle carte de commande </h1>

<%= form_for @control_card, url: admin_control_cards_path, method: :post do |f| %>
<div class="form-group col-md-12">
	<%= f.label :serial_nbr, "Numéro de série" %> : <%= f.text_field :serial_nbr, autofocus: true %><br/>
	</div>
	<div class="form-group col-md-12">
	<%= f.label :school_id, "École liée" %> : <%= f.select :school_id, @linkable_schools.collect{|t| ["#{t.name} - #{t.town}", t.id]}, {prompt: "Choisir une école"} %> <br/>
	</div>
	<%= f.submit "Créer",class: 'btn btn-default' %>
	<%= render partial: "return_link" %>
<% end %>


</div>
</div>

Plante/app/views/admin/control_cards/show.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 transparent-co" style="text-align: center">
<h1> Carte de commande : <%= @control_card.serial_nbr.to_s %> </h1>

Numéro de série de la carte : <%= @control_card.serial_nbr.to_s %><br/>
École liée : <% unless @linked_school.blank? %> <%= @linked_school.name.capitalize.to_s %> <% else %> AUCUNE <% end %><br/>
Nombre de cartes secondaires liées : ...<br/>
<br/>
<%= link_to "Modifier", edit_admin_control_card_path, class: 'btn btn-default' %>
<%= render partial: "return_link" %>
</div>
</div>